# Generated by Django 2.2.6 on 2019-10-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('loginUserId', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginMap',
            fields=[
                ('mappingID', models.IntegerField(primary_key=True, serialize=False)),
                ('loginId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.LoginUser')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.User')),
            ],
        ),
    ]
