# Generated by Django 2.2.6 on 2019-10-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('activate', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('last_logged_in', models.DateTimeField()),
            ],
        ),
    ]
