version: "3"

services:
  app:
    container_name: app_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app/'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    command: >
      sh -c "react-scripts start"
      sh -c "serve -s build"
     
